# `numpy` practice

In [1]:
import numpy as np

1. Do numpy exercises 6, 8, 9 and 19.

1. numpy exercise 44.

1. A snail curve is defined by the following equation in polar coordinates: $r = a + \cos\phi$. Plot the curve on an $x$-$y$ plane for several values of $a$. (Hint: `np.linspace` creates a linearly spaced array of values)

2. A *cochleoid* curve is defined by the following equation in polar coordinates: $r = a \dfrac{\sin\phi} {\phi }$. Plot the curve on an $x$-$y$ plane. (Hint: use `np.where` to work around division by zero).

3. Given two arrays, `u` and `v`, construct the Cauchy matrix using broadcasting.

4. See "Monte Carlo Error propagation" (separate html)

# Exercise 6 
## Можно переприсваивать элементы

In [3]:
import numpy as np
Z = np.zeros(10)

Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Exercise 8
## Наоборот массив записываем

In [6]:
Z = np.arange(50)
Z = Z[::-1] 
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


# Exercise 9
## Можно задавать таким образом массивчик 

In [11]:
Z = np.arange(12).reshape(3,4) # 
print(Z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Exercise 19
## 

In [21]:
Z = np.zeros((8,8),dtype=int)
# Z[1::2,::2] = 1
Z[2::3,1::2] = 1 # 1ый отвечает за нач. строку, второй - столбец и третий за шаги
print(Z)
# x[5::-2] # каждый второй элемент в обратном порядке,
# начиная с индекса 5

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
